---
name: Checks

on:
  push:
    branches: [main]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to docker hub
        uses: docker/login-action@v2
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checking out
        uses: actions/checkout@v2
      - name: Testing
        run: docker compose run --rm app sh -c "python manage.py test"
      - name: Linting
        run: docker compose run --rm app sh -c "flake8"
